/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finaljava;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import project.*;
import java.lang.Runtime;


/**
 *
 * @author Minanga Methlini
 */
public class customerCheckout extends javax.swing.JFrame {

    /**
     * Creates new form customerCheckout
     */
    public customerCheckout() {
        initComponents();
        
        custnm.setEditable(false);
        custcont.setEditable(false);
        custemail.setEditable(false);
        bookeddt.setEditable(false);
        checkoutdt.setEditable(false);
        priceprdy.setEditable(false);
        numOfDy.setEditable(false);
        totlamount.setEditable(false);
    }
    
    int id = 0;
    String Query;
    String cgId;
    String cggender;
    String dh;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtCid = new javax.swing.JTextField();
        custnm = new javax.swing.JTextField();
        bookeddt = new javax.swing.JTextField();
        checkoutdt = new javax.swing.JTextField();
        custcont = new javax.swing.JTextField();
        totlamount = new javax.swing.JTextField();
        priceprdy = new javax.swing.JTextField();
        numOfDy = new javax.swing.JTextField();
        custemail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/window-close-regular.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 39, -1));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 80, 40));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Checkout");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 80, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 101, -1, 40));

        txtCid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidActionPerformed(evt);
            }
        });
        getContentPane().add(txtCid, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 110, 300, -1));

        custnm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(custnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 193, -1));

        bookeddt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(bookeddt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 193, -1));

        checkoutdt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(checkoutdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 196, -1));

        custcont.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(custcont, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 196, -1));

        totlamount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(totlamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 196, -1));

        priceprdy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(priceprdy, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 194, -1));

        numOfDy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(numOfDy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 193, -1));

        custemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(custemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 194, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Contact", "ID number", "Email", "Address", "Gender", "Booked Date", "Caregiver Id", "Caregiver Gender", "Duty Hours", "Price Per Day"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 479, 850, 180));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user-detail-w.png"))); // NOI18N
        jLabel1.setText("Checkouts");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 254, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contact Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Booked Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Checkout Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Price Per Day");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Number of Days");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Amount");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Enter Caregiver ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg mngerrrr.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // form comp
        
        ResultSet rs = select.getData("select * from customer where checkout is NULL");
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        try
        {
            while (rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12)});
            }
            rs.close();
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_formComponentShown

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //search btn
        
        String cId = txtCid.getText();
        
        try
        {
            ResultSet rs = select.getData("select * from customer where CaregiverId = '"+cId+"' and checkout is NULL");
            
            if (rs.next())
            {
                txtCid.setEditable(false);
                id = rs.getInt(1);
                
                custnm.setText(rs.getString(2));
                custcont.setText(rs.getString(3));
                bookeddt.setText(rs.getString(8));
                priceprdy.setText(rs.getString(12));
                
                SimpleDateFormat myFormat = new SimpleDateFormat("yyyy / MM / dd");
                Calendar cal = Calendar.getInstance();
                checkoutdt.setText(myFormat.format(cal.getTime()));
                
                String dateBeforeString = rs.getString(8);
                java.util.Date dateBefore = myFormat.parse(dateBeforeString);
                
                String dateAfterString = myFormat.format(cal.getTime());
                java.util.Date dateAfter = myFormat.parse(dateAfterString);
                
                long deference = dateAfter.getTime() - dateBefore.getTime();
                
                int numbOfDys = (int) (deference / (1000 * 60 * 60 * 24));
                
                if (numbOfDys == 0)
                    numbOfDys = 1;
                
                numOfDy.setText(String.valueOf(numbOfDys));
                float price = Float.parseFloat(priceprdy.getText());
                    
                totlamount.setText(String.valueOf(numbOfDys * price));
                    
                custemail.setText(rs.getString(5));
                    
                cggender = rs.getString(10);
                dh = rs.getString(11);
            }
            else 
            {
                JOptionPane.showMessageDialog(null, "Caregiver is not Booked or Caregiver does not Exist");
            }
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // checkout btn
        
        String name = custnm.getText();
        String mobile = custcont.getText();
        String email = custemail.getText();
        
        String checkout = checkoutdt.getText();
        String numbofdys = numOfDy.getText();
        String ttlamount = totlamount.getText();
        
        cgId = txtCid.getText();
        
        Query = "update customer set numberOfDaye = '"+numbofdys+"', totalAmount = '"+ttlamount+"', checkout = '"+checkout+"' where id = '"+id+"'";
        InsertUpdateDelete.setData(Query, "");
        
        Query = "update caregiver set status = 'Not Booked' where caregiverId = '"+cgId+"'";
        InsertUpdateDelete.setData(Query, "");
        
        String path = "D:\\";
        
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        
        try
        {
            PdfWriter.getInstance(doc, new FileOutputStream (path + ""+id+".pdf"));
            doc.open();
        
            Paragraph paragraph1 = new Paragraph("                                                   Caregiver Management System");
            doc.add(paragraph1);
            
            Paragraph paragraph2 = new Paragraph("***************************************************************************************************************");
            doc.add(paragraph2);
            
            Paragraph paragraph3 = new Paragraph("\tBill Id : "+id+" \nCustomer Details \nName:"+name+"\nContact Number : "+mobile+"\nEmail Address : "+email+"");
            doc.add(paragraph3);
            doc.add(paragraph2);
            
            Paragraph paragraph4 = new Paragraph("\tCaregiver Details \nID :"+txtCid.getText()+"\nGender : "+cggender+"\nDuty Hour : "+dh+"\nPrice per Day : "+priceprdy.getText()+"");
            doc.add(paragraph4);
            doc.add(paragraph2);
            
            PdfPTable tbl = new PdfPTable(4);
            tbl.addCell("Booked Date:"+bookeddt.getText()+"");
            tbl.addCell("Checkout Date:"+checkout+"");
            tbl.addCell("Number of Days:"+numbofdys+"");
            tbl.addCell("Total Charges:"+ttlamount+"");
            doc.add(tbl);
            
            doc.add(paragraph2);
            
            Paragraph paragraph5 = new Paragraph("Thank you. Please Contact Us Again");
            doc.add(paragraph5); 
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        doc.close();
        
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Print This Bill ?","Select",JOptionPane.YES_NO_OPTION);
        
        if (a == 0)
        {
            try
            {
                if ((new File("D:\\"+id+".pdf")).exists())
                {
                    Process p = Runtime
                            .getRuntime()
                            .exec("rundll32 url.dll,FileProtocolHandler D:// " + id + ".pdf");
                }
                else
                {
                    System.out.println("File is not exist");
                }
            }
            
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        setVisible(false);
        new hmpg().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // close btn
        setVisible(false);
        new hmpg().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerCheckout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookeddt;
    private javax.swing.JTextField checkoutdt;
    private javax.swing.JTextField custcont;
    private javax.swing.JTextField custemail;
    private javax.swing.JTextField custnm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField numOfDy;
    private javax.swing.JTextField priceprdy;
    private javax.swing.JTextField totlamount;
    private javax.swing.JTextField txtCid;
    // End of variables declaration//GEN-END:variables
}
